handlers=java.util.logging.ConsoleHandler
.level=INFO
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter

org.openqa.selenium.manager.SeleniumManager.level=SEVERE
org.openqa.selenium.devtools.CdpVersionFinder.level=SEVERE
org.openqa.selenium.chromium.ChromiumDriver.level=SEVERE
