appiumServerUrl=http://127.0.0.1:4723
androidDeviceName=emulator-5554
androidPlatformName=Android
androidAutomationName=UiAutomator2
androidInstallApp=false
androidPreLaunchWithAdb=true
androidClearAppDataBeforeLaunch=true
androidAutoLaunch=false
androidDontStopAppOnReset=true
androidSkipDeviceInitialization=true
androidDisableWindowAnimation=true
androidAppPath=C:\\AppiumApps\\maintenxs.apk
androidAppPackage=com.example.Maintenxs
androidAppActivity=.MainActivity
androidNoReset=true
